spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
sentry:
  dsn: https://ca727f56e2174289f4ac6e3457761a5b@o4509598314463232.ingest.de.sentry.io/4509598325080144
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true